version: '3.1'
services:
  db:
    image: mysql:8.0.28-oracle
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: dbblog
      MYSQL_USER: dbblog
      MYSQL_PASSWORD: pass